import BackToTop from "@/BackToTop";
import "./globals.css";
import ScrollToTop from "@/ScrollToTop";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body className="min-h-screen bg-slate-950 text-white">
        <ScrollToTop  />
        {children}
        <BackToTop />
      </body>
    </html>
  );
}
